apiVersion: game.laputacloud.co/v1alpha1
kind: Minecraft
metadata:
  name: sample
spec:
  config:
    EULA: "TRUE"
    TZ: US/New York
    VERSION: LATEST
    WHITELIST: Erock3r
  storageSize: 8Gi
  storageClassName: singlewriter-standard
  serve: true
  cpu: 500m
  memory: 768Mi