// +build !ignore_autogenerated

/*
Copyright 2021 The Laputa Cloud Co.

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
*/

// Code generated by controller-gen. DO NOT EDIT.

package types

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameOptions) DeepCopyInto(out *GameOptions) {
	*out = *in
	if in.GeneratorSettings != nil {
		in, out := &in.GeneratorSettings, &out.GeneratorSettings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mods != nil {
		in, out := &in.Mods, &out.Mods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ops != nil {
		in, out := &in.Ops, &out.Ops
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameOptions.
func (in *GameOptions) DeepCopy() *GameOptions {
	if in == nil {
		return nil
	}
	out := new(GameOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerOptions) DeepCopyInto(out *ServerOptions) {
	*out = *in
	if in.SpigetResources != nil {
		in, out := &in.SpigetResources, &out.SpigetResources
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerOptions.
func (in *ServerOptions) DeepCopy() *ServerOptions {
	if in == nil {
		return nil
	}
	out := new(ServerOptions)
	in.DeepCopyInto(out)
	return out
}
