name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, v1alpha2 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: test
      run: make test


